include:
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-base.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-dom0.yml'
  - project: 'QubesOS/qubes-continuous-integration'
    file: '/r4.1/gitlab-vm.yml'

checks:pylint:
  stage: checks
  before_script:
    - sudo dnf install -y python3-gobject gtk3 xorg-x11-server-Xvfb
    - pip3 install --quiet -r ci/requirements.txt
    - git clone https://github.com/QubesOS/qubes-core-admin-client ~/core-admin-client
  script:
    - PYTHONPATH=~/core-admin-client python3 -m pylint --rcfile=.pylintrc qui



